name: KEIR
favicon: null
layout_spectrum: 0.99807
typography_spectrum: 0.46298
title: KEIR
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1a1b'
    - '#747474'
    - '#b6b6b6'
    - '#505050'
  brandStrength: 0.8379690502770245
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
